name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  PyTests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ]
        python-version: ["3.10", "3.11", "3.12", ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install .[bench] pytest
      - name: Pytest
        run: pytest -v tests
